package COMMUNICATION;

/** Response object for /user/login
 *
 * @author Rees Thomas
 *
 */
public class LoginResult
{
    /** Create a new LoginResult object
     *
     * @param authToken
     * @param username
     * @param personID
     *
     */
    public LoginResult(String authToken, String username, String personID)
    {
        this.authToken = authToken;
        this.username = username;
        this.personID = personID;
    }

    /** AuthToken generated by user's login
     *
     */
    public String authToken;

    /** User's specified username
     *
     */
    public String username;

    /** User's personID of assigned Person object
     *
     */
    public String personID;

    /** Failure message
     *
     */
    public String message;

    public String getAuthToken()
    {
        return authToken;
    }

    public void setAuthToken(String authToken)
    {
        this.authToken = authToken;
    }

    public String getUsername()
    {
        return username;
    }

    public void setUsername(String username)
    {
        this.username = username;
    }

    public String getPersonID()
    {
        return personID;
    }

    public void setPersonID(String personID)
    {
        this.personID = personID;
    }

    public String getErrorMessage()
    {
        return message;
    }

    public void setErrorMessage(String errorMessage)
    {
        this.message = errorMessage;
    }
}
